pipeline:
  lint:
    group: prebuild
    image: python:3.7
    commands:
      - pip3 install flake8
      - flake8
    when:
      event: push

  run_tests:
    group: prebuild
    image: python:3.7
    commands:
      - apt-get update
      - apt-get -qq install alien build-essential libssl-dev libffi-dev tox -y
      - make install
      - make test
    when:
      event: push

  build_dev:
    image: plugins/docker
    tag: dev-env
    dockerfile: Dockerfile
    target: dev
    repo: docker.netsoc.co/public/netsocadmin
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]
      branch: master 

  build_prod:
    image: plugins/docker
    tag: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/netsoc/netsocadmin
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]
      branch: master
