pipeline:
  run_tests:
    image: hostedgraphite/pythonbuild:xenial_python3
    commands:
      - apt-get -qq install alien build-essential libssl-dev libffi-dev -y
      - make install
      - make test
    when:
      event: push

  build_and_push:
    image: plugins/docker
    tag: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/netsocadmin
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]
      branch: master
