pipeline:
  test_build:
    image: hostedgraphite/pythonbuild:xenial_python3
    environment:
      ARTIFACTS: /tmp/artifacts
    commands:
      - apt-get update
      - apt-get install build-essential libssl-dev libffi-dev -y
      - mkdir -p $ARTIFACTS
      - make install
      - make test
      - make release
      - ls -alt .
      - ls -alt $ARTIFACTS
      - cp -r cover $ARTIFACTS
      - cp ../*.deb $ARTIFACTS
      - ls -alt $ARTIFACTS
  test_joining:
    image: hostedgraphite/pythonbuild:xenial_python3
    commands:
      - ls -alt .
      - ls -alt /tmp/artifacts
  build_and_push:
    image: plugins/docker
    tag: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/netsocadmin
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]
      branch: master
