pipeline:
  build_and_push:
    image: plugins/docker
    tag: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/netsocadmin
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]
      branch: master
  test_build:
    image: hostedgraphite/pythonbuild:3
    dockerfile: Dockerfile
    environment:
      ARTIFACTS: /tmp/artifacts
    commands:
      - mkdir -p $ARTIFACTS
      - make install
      - make test
      - make release
      - cp -r cover $ARTIFACTS
      - cp ../*.deb $ARTIFACTS
