pipeline:
  test_build:
    image: hostedgraphite/pythonbuild:xenial_python3
    environment:
      ARTIFACTS: /tmp/artifacts
    secrets: [ ci_obj_access_key, ci_obj_secret_key, ci_obj_location ]
    commands:
      - apt-get -qq install build-essential libssl-dev libffi-dev -y
      - mkdir -p ARTIFACTS
      - make install
      - make test
      - make release
      - cp -r cover ARTIFACTS
      - cp ../*.deb ARTIFACTS
      - ls -alt ./.ci
      - make upload
  build_and_push:
    image: plugins/docker
    tag: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/netsocadmin
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]
      branch: master
