pipeline:
  lint:
    image: python:3.7
    commands:
      - pip3 install flake8
      - flake8
    when:
      event: push
  run_tests:
    image: python:3.7
    commands:
      - apt-get update
      - apt-get -qq install alien build-essential libssl-dev libffi-dev tox -y
      - make install
      - make test
    when:
      event: push

  build_and_push:
    image: plugins/docker
    tag: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/netsocadmin
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]
      branch: master
