kind: pipeline
name: default

steps:
- lint:
  image: python:3.7
  commands:
    - pip3 install flake8
    - flake8
  when:
    event: 
      - push

- build_dev:
  image: plugins/docker
  settings:
    tag: dev-env
    target: dev
    repo: docker.netsoc.co/public/netsocadmin
    registry: docker.netsoc.co
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event: 
      - push
    branch: 
      - master 

- build_prod:
  image: plugins/docker
  settings:
    tag: latest
    repo: docker.netsoc.co/public/netsocadmin
    registry: docker.netsoc.co
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event: 
      - push
    branch: 
      - master 

- discord_notif:
  image: appleboy/drone-discord
  environment:
    WEBHOOK_ID:
      from_secret: discord_webhook_id
    WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  settings:
    username: Netsoc CI
    avatar_url: https://noahsc.xyz/public_images/drone.png
    color: "#42f483"
    message: >
      {{#success build.status}}
        Netsoc Admin successfully built and pushed. Build num {{build.number}}.
      {{else}}
        Netsoc Admin failed to build. Build num {{build.number}}.
      {{/success}}    
  when:
    event: 
      - push
    branch: 
      - master 